// SPDX-License-Identifier: Apache-2.0
//
// StitcherFrameHostObject.mm — iOS-specific wrapper for the shared
// `retailens::StitcherFrameJsiHostObject` (defined in
// `cpp/stitcher_frame_jsi.{hpp,cpp}`).
//
// Owns:
//   - The Obj-C facade callable from Swift / other Obj-C / .mm files.
//   - The iOS-specific `PixelBufferReader` impl (wraps a
//     `CVPixelBufferRef` from `ARFrame.capturedImage`; lock / memcpy
//     / unlock pattern).
//   - The Obj-C → C++ extraction logic that builds a
//     `retailens::StitcherFrameData` from an `ARFrame` + the lib's
//     `RNSARFramePose`.
//
// Does NOT own:
//   - The JSI `get` / `getPropertyNames` dispatch.  That lives in
//     `cpp/stitcher_frame_jsi.cpp` and is identical to the Android
//     implementation (DRY across platforms).

#import "StitcherFrameHostObject.h"

#import <Foundation/Foundation.h>
#import <ARKit/ARKit.h>
#import <CoreVideo/CVPixelBuffer.h>
#import <CoreMedia/CoreMedia.h>
#import <simd/simd.h>
#import <os/log.h>

#include <jsi/jsi.h>

#include <algorithm>
#include <cstring>
#include <memory>
#include <string>
#include <utility>

#include "stitcher_frame_data.hpp"
#include "stitcher_frame_jsi.hpp"

using namespace facebook;

// Forward-declare the Swift `RNSARFramePose` Obj-C surface we need.
// This matches the pattern in `KeyframeGateFrameProcessor.mm`
// (forward-declaring `IncrementalStitcher`) — avoids depending on
// the autogenerated `RNImageStitcher-Swift.h`, which is created at
// build time and not always available to .mm files in this pod.
//
// MUST stay in sync with `RNSARSession.swift::RNSARFramePose` —
// adding a new field there means adding it here too.
@class RNSARFramePose;
@interface RNSARFramePose : NSObject
@property (nonatomic, readonly) double tx;
@property (nonatomic, readonly) double ty;
@property (nonatomic, readonly) double tz;
@property (nonatomic, readonly) double qx;
@property (nonatomic, readonly) double qy;
@property (nonatomic, readonly) double qz;
@property (nonatomic, readonly) double qw;
@property (nonatomic, readonly) NSInteger imageWidth;
@property (nonatomic, readonly) NSInteger imageHeight;
@property (nonatomic, readonly) double timestampMs;
@end

#pragma mark - iOS PixelBufferReader

namespace {

/// iOS-specific `retailens::PixelBufferReader` impl.  See the base
/// class docstring for the general contract (thread-affinity,
/// invalidation semantics, Y-plane-only constraint).  This subclass
/// adds:
///   - `CVPixelBuffer` lock/memcpy/unlock per copyTo
///   - `CFBridgingRetain` of the parent `ARFrame` so ARKit's
///     pool can't reclaim the underlying buffer mid-read
class IOSPixelBufferReader : public retailens::PixelBufferReader {
 public:
  explicit IOSPixelBufferReader(ARFrame* arFrame) {
    // Retain the ARFrame for our lifetime.  CFBridgingRetain hands
    // ARC ownership to our void*.  Released in destructor.
    _retainedFrame = (void*)CFBridgingRetain(arFrame);
    CVPixelBufferRef pixelBuffer = arFrame.capturedImage;
    if (pixelBuffer != NULL) {
      _bytesPerRow = CVPixelBufferGetBytesPerRow(pixelBuffer);
      _height = CVPixelBufferGetHeight(pixelBuffer);
    }
  }

  ~IOSPixelBufferReader() override {
    // Transfer ownership back to ARC, which then releases.
    if (_retainedFrame != nullptr) {
      ARFrame* frame = CFBridgingRelease(_retainedFrame);
      (void)frame;
      _retainedFrame = nullptr;
    }
  }

  std::size_t byteSize() const override {
    return _bytesPerRow * _height;
  }

  std::size_t copyTo(uint8_t* dst, std::size_t maxBytes) override {
    if (_retainedFrame == nullptr) return 0;
    ARFrame* frame = (__bridge ARFrame*)_retainedFrame;
    CVPixelBufferRef pixelBuffer = frame.capturedImage;
    if (pixelBuffer == NULL) return 0;

    CVPixelBufferLockBaseAddress(pixelBuffer, kCVPixelBufferLock_ReadOnly);
    const uint8_t* src = (const uint8_t*)CVPixelBufferGetBaseAddress(pixelBuffer);
    std::size_t toCopy = std::min<std::size_t>(byteSize(), maxBytes);
    if (src != nullptr && toCopy > 0) {
      std::memcpy(dst, src, toCopy);
    } else {
      toCopy = 0;
    }
    CVPixelBufferUnlockBaseAddress(pixelBuffer, kCVPixelBufferLock_ReadOnly);
    return toCopy;
  }

 private:
  void* _retainedFrame = nullptr;   // CFBridgingRetain'd ARFrame
  std::size_t _bytesPerRow = 0;
  std::size_t _height = 0;
};

#pragma mark - AR depth + anchor extraction

/// Copy a single-channel CVPixelBuffer into a TIGHTLY-PACKED byte
/// vector, stripping any per-row padding.  ARKit's depth/confidence
/// maps frequently have `bytesPerRow > width * elementSize` (rows are
/// padded for alignment), so a bulk `memcpy(base, w*h*elemSize)` would
/// copy garbage padding bytes into the wrong positions and shear the
/// map.  We copy `width * elementSize` bytes per row from `base +
/// row * bytesPerRow` so the result is row-packed exactly as the
/// shared JSI layer (`stitcher_frame_jsi.cpp`) expects.
///
/// Returns `true` on success (out is filled with `w*h*elementSize`
/// bytes); `false` if the buffer couldn't be locked or has no base
/// address (out is left untouched).
bool PackSingleChannelPixelBuffer(CVPixelBufferRef buffer,
                                  std::size_t elementSize,
                                  std::vector<uint8_t>& out) {
  if (buffer == NULL) return false;
  if (CVPixelBufferLockBaseAddress(buffer, kCVPixelBufferLock_ReadOnly) !=
      kCVReturnSuccess) {
    return false;
  }
  const std::size_t width = CVPixelBufferGetWidth(buffer);
  const std::size_t height = CVPixelBufferGetHeight(buffer);
  const std::size_t bytesPerRow = CVPixelBufferGetBytesPerRow(buffer);
  const uint8_t* base =
      reinterpret_cast<const uint8_t*>(CVPixelBufferGetBaseAddress(buffer));
  const std::size_t rowBytes = width * elementSize;

  bool ok = false;
  if (base != nullptr && width > 0 && height > 0 && bytesPerRow >= rowBytes) {
    out.resize(rowBytes * height);
    for (std::size_t row = 0; row < height; ++row) {
      std::memcpy(out.data() + row * rowBytes,
                  base + row * bytesPerRow,
                  rowBytes);
    }
    ok = true;
  }
  CVPixelBufferUnlockBaseAddress(buffer, kCVPixelBufferLock_ReadOnly);
  return ok;
}

/// Extract ARKit `sceneDepth` (preferred) / `smoothedSceneDepth` into
/// the shared `ArDepth` struct as `format="f32m"`:
///   - depthBytes    = Float32 metres, row-packed (w*h*4 bytes)
///   - confidenceBytes = Uint8 ARConfidenceLevel 0..2, row-packed (w*h)
/// `width`/`height` are the DEPTH MAP's own dimensions (≈256x192),
/// NOT the camera image's — the JSI layer derives `px = w*h` from
/// these to validate the byte counts.  Leaves `data.arDepth` as
/// `nullopt` when the device/session provides no depth (non-LiDAR
/// devices, or before the first depth frame arrives).
void ExtractARDepth(ARFrame* arFrame, retailens::StitcherFrameData& data) {
  ARDepthData* dd = arFrame.sceneDepth;
  if (dd == nil) dd = arFrame.smoothedSceneDepth;
  if (dd == nil) return;

  CVPixelBufferRef depthMap = dd.depthMap;   // kCVPixelFormatType_DepthFloat32
  if (depthMap == NULL) return;
  const int32_t w = static_cast<int32_t>(CVPixelBufferGetWidth(depthMap));
  const int32_t h = static_cast<int32_t>(CVPixelBufferGetHeight(depthMap));
  if (w <= 0 || h <= 0) return;

  std::vector<uint8_t> depthBytes;
  if (!PackSingleChannelPixelBuffer(depthMap, sizeof(float), depthBytes)) {
    return;
  }

  // Confidence is optional (some configs/devices omit it).  When
  // present it's a Uint8 ARConfidenceLevel (0=low,1=medium,2=high),
  // same w*h dimensions as the depth map.  Leave empty on failure —
  // the JSI layer treats an empty confidence buffer as "no
  // confidenceMap" (matching the JS `confidenceMap?` optional).
  std::vector<uint8_t> confidenceBytes;
  CVPixelBufferRef conf = dd.confidenceMap;  // kCVPixelFormatType_ConfidenceUint8
  if (conf != NULL) {
    if (!PackSingleChannelPixelBuffer(conf, sizeof(uint8_t), confidenceBytes)) {
      confidenceBytes.clear();
    }
  }

  retailens::ArDepth out;
  out.width = w;
  out.height = h;
  out.format = "f32m";
  out.depthBytes = std::move(depthBytes);
  out.confidenceBytes = std::move(confidenceBytes);
  data.arDepth = std::move(out);
}

/// Extract the frame's tracked anchors into the shared `ArAnchor`
/// vector.  Each anchor carries a stable id, a coarse type
/// (`"plane"` / `"image"` / `"point"`), and a 4x4 anchor->world
/// transform emitted ROW-MAJOR.  ARKit's `simd_float4x4` is
/// COLUMN-MAJOR (`columns[c][r]`), so we transpose:
/// `transform[r*4+c] = a.transform.columns[c][r]`.
void ExtractARAnchors(ARFrame* arFrame, retailens::StitcherFrameData& data) {
  NSArray<ARAnchor*>* anchors = arFrame.anchors;
  data.arAnchors.reserve(anchors.count);
  for (ARAnchor* a in anchors) {
    retailens::ArAnchor out;
    out.id = std::string(a.identifier.UUIDString.UTF8String);
    if ([a isKindOfClass:[ARPlaneAnchor class]]) {
      out.type = "plane";
    } else if ([a isKindOfClass:[ARImageAnchor class]]) {
      out.type = "image";
    } else {
      out.type = "point";
    }
    const simd_float4x4 m = a.transform;
    for (int r = 0; r < 4; ++r) {
      for (int c = 0; c < 4; ++c) {
        out.transform[r * 4 + c] = static_cast<double>(m.columns[c][r]);
      }
    }
    data.arAnchors.push_back(std::move(out));
  }
}

}  // anonymous namespace

#pragma mark - Obj-C facade

@implementation StitcherFrameHostObject {
  std::shared_ptr<retailens::StitcherFrameJsiHostObject> _hostObject;
}

+ (instancetype)fromARFrame:(ARFrame*)arFrame pose:(RNSARFramePose*)pose {
  StitcherFrameHostObject* obj = [[self alloc] init];

  retailens::StitcherFrameData data;
  data.source = "ar";
  data.width = static_cast<int32_t>(pose.imageWidth);
  data.height = static_cast<int32_t>(pose.imageHeight);
  // ARKit's `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange` (NV12)
  // is reported as "yuv".  Other formats (rare in ARKit; possible if
  // ARWorldTrackingConfiguration.videoFormat is overridden to BGRA)
  // → "unknown" + os_log warning so worklets that gate on
  // `pixelFormat === 'yuv'` can be debugged without a screen recording.
  OSType pf = CVPixelBufferGetPixelFormatType(arFrame.capturedImage);
  if (pf == kCVPixelFormatType_420YpCbCr8BiPlanarFullRange ||
      pf == kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange) {
    data.pixelFormat = "yuv";
  } else {
    data.pixelFormat = "unknown";
    os_log_error(OS_LOG_DEFAULT,
        "[StitcherFrame] unexpected ARKit pixel format 0x%x; "
        "worklet receives pixelFormat='unknown' and toArrayBuffer() "
        "bytes are first-plane only (layout undefined for unknown "
        "formats).  See StitcherFrame.ts docstring.", (unsigned int)pf);
  }
  // ARKit doesn't have a `Frame.orientation` per se; pose carries
  // the imageWidth >= imageHeight discriminator the lib uses
  // elsewhere (`isLandscape`).  v0.8.0 ships a coarse mapping;
  // worklets that need exact UI orientation can read it from
  // device-orientation sensors.
  data.orientation =
      (pose.imageWidth >= pose.imageHeight) ? "landscape-right" : "portrait";
  // `ARFrame.timestamp` is CFAbsoluteTime (seconds since epoch).
  // Convert to ns to match vc Frame.timestamp.
  data.timestampNs = arFrame.timestamp * 1e9;

  data.qx = pose.qx;
  data.qy = pose.qy;
  data.qz = pose.qz;
  data.qw = pose.qw;
  data.tx = pose.tx;
  data.ty = pose.ty;
  data.tz = pose.tz;
  data.hasTranslation = true;   // AR mode always has translation

  switch (arFrame.camera.trackingState) {
    case ARTrackingStateNotAvailable:
      data.arTrackingState = "notAvailable";
      break;
    case ARTrackingStateLimited:
      data.arTrackingState = "limited";
      break;
    case ARTrackingStateNormal:
      data.arTrackingState = "normal";
      break;
  }

  data.pixelReader = std::make_shared<IOSPixelBufferReader>(arFrame);

  // AR depth + anchors.  Both EAGER-COPY out of the ARFrame here (the
  // depth/confidence bytes are packed into owned vectors; anchor
  // transforms are read into std::array), so neither depends on the
  // ARFrame's lifetime the way the pixel reader does.  Depth is
  // nullopt on non-LiDAR devices / before the first depth frame;
  // anchors is an empty vector when none are tracked.
  ExtractARDepth(arFrame, data);
  ExtractARAnchors(arFrame, data);

  // Use the static factory (private ctor enforces shared_ptr
  // ownership — required for `shared_from_this()` inside the JSI
  // `toArrayBuffer` lambda).
  obj->_hostObject =
      retailens::StitcherFrameJsiHostObject::create(std::move(data));
  return obj;
}

- (void)invalidate {
  if (_hostObject) {
    _hostObject->invalidate();
  }
}

- (void*)jsiHostObjectPtr {
  if (!_hostObject) return NULL;
  // Box a heap-allocated copy of the shared_ptr to the abstract
  // `jsi::HostObject` base.  Caller (worklet runtime) does:
  //   auto sp = static_cast<std::shared_ptr<jsi::HostObject>*>(ptr);
  //   auto jsObj = jsi::Object::createFromHostObject(rt, *sp);
  //   delete sp;
  return new std::shared_ptr<jsi::HostObject>(_hostObject);
}

@end
