// SPDX-License-Identifier: Apache-2.0
//
// StitcherFrameHostObject.mm — iOS-specific wrapper for the shared
// `retailens::StitcherFrameJsiHostObject` (defined in
// `cpp/stitcher_frame_jsi.{hpp,cpp}`).
//
// Owns:
//   - The Obj-C facade callable from Swift / other Obj-C / .mm files.
//   - The iOS-specific `PixelBufferReader` impl (wraps a
//     `CVPixelBufferRef` from `ARFrame.capturedImage`; lock / memcpy
//     / unlock pattern).
//   - The Obj-C → C++ extraction logic that builds a
//     `retailens::StitcherFrameData` from an `ARFrame` + the lib's
//     `RNSARFramePose`.
//
// Does NOT own:
//   - The JSI `get` / `getPropertyNames` dispatch.  That lives in
//     `cpp/stitcher_frame_jsi.cpp` and is identical to the Android
//     implementation (DRY across platforms).

#import "StitcherFrameHostObject.h"

#import <Foundation/Foundation.h>
#import <CoreVideo/CVPixelBuffer.h>
#import <CoreMedia/CoreMedia.h>

#include <jsi/jsi.h>

#include <algorithm>
#include <cstring>
#include <memory>
#include <string>
#include <utility>

#include "stitcher_frame_data.hpp"
#include "stitcher_frame_jsi.hpp"

using namespace facebook;

// Forward-declare the Swift `RNSARFramePose` Obj-C surface we need.
// This matches the pattern in `KeyframeGateFrameProcessor.mm`
// (forward-declaring `IncrementalStitcher`) — avoids depending on
// the autogenerated `RNImageStitcher-Swift.h`, which is created at
// build time and not always available to .mm files in this pod.
//
// MUST stay in sync with `RNSARSession.swift::RNSARFramePose` —
// adding a new field there means adding it here too.
@class RNSARFramePose;
@interface RNSARFramePose : NSObject
@property (nonatomic, readonly) double tx;
@property (nonatomic, readonly) double ty;
@property (nonatomic, readonly) double tz;
@property (nonatomic, readonly) double qx;
@property (nonatomic, readonly) double qy;
@property (nonatomic, readonly) double qz;
@property (nonatomic, readonly) double qw;
@property (nonatomic, readonly) NSInteger imageWidth;
@property (nonatomic, readonly) NSInteger imageHeight;
@property (nonatomic, readonly) double timestampMs;
@end

#pragma mark - iOS PixelBufferReader

namespace {

/// iOS-specific `PixelBufferReader`.  Locks the `CVPixelBuffer`'s
/// base address on each `copyTo`, copies the (Y-plane) bytes, then
/// unlocks.  Holds a strong reference to the parent `ARFrame` so
/// the underlying `CVPixelBuffer` (owned by ARKit's pool) doesn't
/// get reclaimed mid-read.
///
/// v0.8.0: emits the Y plane only.  Full chroma (NV12 UV plane,
/// BGRA, etc.) deferred until a host worklet needs it.
class IOSPixelBufferReader : public retailens::PixelBufferReader {
 public:
  explicit IOSPixelBufferReader(ARFrame* arFrame) {
    // Retain the ARFrame for our lifetime.  CFBridgingRetain hands
    // ARC ownership to our void*.  Released in destructor.
    _retainedFrame = (void*)CFBridgingRetain(arFrame);
    CVPixelBufferRef pixelBuffer = arFrame.capturedImage;
    if (pixelBuffer != NULL) {
      _bytesPerRow = CVPixelBufferGetBytesPerRow(pixelBuffer);
      _height = CVPixelBufferGetHeight(pixelBuffer);
    }
  }

  ~IOSPixelBufferReader() override {
    // Transfer ownership back to ARC, which then releases.
    if (_retainedFrame != nullptr) {
      ARFrame* frame = CFBridgingRelease(_retainedFrame);
      (void)frame;
      _retainedFrame = nullptr;
    }
  }

  std::size_t byteSize() const override {
    return _bytesPerRow * _height;
  }

  std::size_t copyTo(uint8_t* dst, std::size_t maxBytes) override {
    if (_retainedFrame == nullptr) return 0;
    ARFrame* frame = (__bridge ARFrame*)_retainedFrame;
    CVPixelBufferRef pixelBuffer = frame.capturedImage;
    if (pixelBuffer == NULL) return 0;

    CVPixelBufferLockBaseAddress(pixelBuffer, kCVPixelBufferLock_ReadOnly);
    const uint8_t* src = (const uint8_t*)CVPixelBufferGetBaseAddress(pixelBuffer);
    std::size_t toCopy = std::min<std::size_t>(byteSize(), maxBytes);
    if (src != nullptr && toCopy > 0) {
      std::memcpy(dst, src, toCopy);
    } else {
      toCopy = 0;
    }
    CVPixelBufferUnlockBaseAddress(pixelBuffer, kCVPixelBufferLock_ReadOnly);
    return toCopy;
  }

 private:
  void* _retainedFrame = nullptr;   // CFBridgingRetain'd ARFrame
  std::size_t _bytesPerRow = 0;
  std::size_t _height = 0;
};

}  // anonymous namespace

#pragma mark - Obj-C facade

@implementation StitcherFrameHostObject {
  std::shared_ptr<retailens::StitcherFrameJsiHostObject> _hostObject;
}

+ (instancetype)fromARFrame:(ARFrame*)arFrame pose:(RNSARFramePose*)pose {
  StitcherFrameHostObject* obj = [[self alloc] init];

  retailens::StitcherFrameData data;
  data.source = "ar";
  data.width = static_cast<int32_t>(pose.imageWidth);
  data.height = static_cast<int32_t>(pose.imageHeight);
  // ARKit's `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange` (NV12)
  // is reported as "yuv".  Other formats (rare in ARKit) → "unknown".
  OSType pf = CVPixelBufferGetPixelFormatType(arFrame.capturedImage);
  if (pf == kCVPixelFormatType_420YpCbCr8BiPlanarFullRange ||
      pf == kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange) {
    data.pixelFormat = "yuv";
  } else {
    data.pixelFormat = "unknown";
  }
  // ARKit doesn't have a `Frame.orientation` per se; pose carries
  // the imageWidth >= imageHeight discriminator the lib uses
  // elsewhere (`isLandscape`).  v0.8.0 ships a coarse mapping;
  // worklets that need exact UI orientation can read it from
  // device-orientation sensors.
  data.orientation =
      (pose.imageWidth >= pose.imageHeight) ? "landscape-right" : "portrait";
  // `ARFrame.timestamp` is CFAbsoluteTime (seconds since epoch).
  // Convert to ns to match vc Frame.timestamp.
  data.timestampNs = arFrame.timestamp * 1e9;

  data.qx = pose.qx;
  data.qy = pose.qy;
  data.qz = pose.qz;
  data.qw = pose.qw;
  data.tx = pose.tx;
  data.ty = pose.ty;
  data.tz = pose.tz;
  data.hasTranslation = true;   // AR mode always has translation

  switch (arFrame.camera.trackingState) {
    case ARTrackingStateNotAvailable:
      data.arTrackingState = "notAvailable";
      break;
    case ARTrackingStateLimited:
      data.arTrackingState = "limited";
      break;
    case ARTrackingStateNormal:
      data.arTrackingState = "normal";
      break;
  }

  data.pixelReader = std::make_shared<IOSPixelBufferReader>(arFrame);

  obj->_hostObject =
      std::make_shared<retailens::StitcherFrameJsiHostObject>(std::move(data));
  return obj;
}

- (void)invalidate {
  if (_hostObject) {
    _hostObject->invalidate();
  }
}

- (void*)jsiHostObjectPtr {
  if (!_hostObject) return NULL;
  // Box a heap-allocated copy of the shared_ptr to the abstract
  // `jsi::HostObject` base.  Caller (worklet runtime) does:
  //   auto sp = static_cast<std::shared_ptr<jsi::HostObject>*>(ptr);
  //   auto jsObj = jsi::Object::createFromHostObject(rt, *sp);
  //   delete sp;
  return new std::shared_ptr<jsi::HostObject>(_hostObject);
}

@end
